import { WeatherForecast } from "../types/weather";

export const mockWeatherData: WeatherForecast = {
  current: {
    location: "San Francisco",
    country: "United States",
    temperature: 22,
    condition: "Thunder",
    description: "A beautiful day with some clouds",
    humidity: 65,
    windSpeed: 15,
    pressure: 1013,
    visibility: 10,
    uvIndex: 6,
    sunrise: "06:45",
    sunset: "19:30",
    icon: "partly-cloudy",
  },
  forecast: [
    {
      date: "2025-01-27",
      dayName: "Today",
      high: 24,
      low: 16,
      condition: "Partly Cloudy",
      icon: "partly-cloudy",
      humidity: 65,
      windSpeed: 15,
      precipitation: 10,
    },
    {
      date: "2025-01-28",
      dayName: "Tomorrow",
      high: 26,
      low: 18,
      condition: "Sunny",
      icon: "sunny",
      humidity: 55,
      windSpeed: 12,
      precipitation: 0,
    },
    {
      date: "2025-01-29",
      dayName: "Wednesday",
      high: 21,
      low: 14,
      condition: "Light Rain",
      icon: "rain",
      humidity: 80,
      windSpeed: 18,
      precipitation: 75,
    },
    {
      date: "2025-01-30",
      dayName: "Thursday",
      high: 19,
      low: 12,
      condition: "Cloudy",
      icon: "cloudy",
      humidity: 70,
      windSpeed: 14,
      precipitation: 20,
    },
    {
      date: "2025-01-31",
      dayName: "Friday",
      high: 23,
      low: 15,
      condition: "Partly Cloudy",
      icon: "partly-cloudy",
      humidity: 60,
      windSpeed: 16,
      precipitation: 15,
    },
  ],
};
